apiVersion: apps/v1
kind: Deployment
metadata:
  name: servico-gerenciamento
  labels:
    app: servico-gerenciamento
spec:
  template:
    metadata:
      name: servico-gerenciamento
      labels:
        app: servico-gerenciamento
    spec:
      containers:
        - name: servico-gerenciamento
          image: geter/gerenciamento-techchallenge38:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: ${DB_HOST}
            - name: DB_USER
              value: ${DB_USER}
            - name: DB_PASS
              value: ${DB_PASS}
            - name: ENV
              value: ${ENV}
          volumeMounts:
            - mountPath: /servico-gerenciamento-volume
              name: servico-gerenciamento-volume
      volumes:
        - name: servico-gerenciamento-volume
          hostPath:
            path: /home/servico-gerenciamento-volume
            type: DirectoryOrCreate
      serviceAccountName: gerenciamento-serviceaccount
  replicas: 2
  selector:
    matchLabels:
      app: servico-gerenciamento
