apiVersion: apps/v1
kind: Deployment
metadata:
  name: servico-lanchonete
  labels:
    app: servico-lanchonete
spec:
  template:
    metadata:
      name: servico-lanchonete
      labels:
        app: servico-lanchonete
    spec:
      containers:
        - name: servico-lanchonete
          image: geter/lanchonete-techchallenge38:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: ${DB_HOSTNAME}
            - name: DB_USER
              value: ${DB_USERNAME}
            - name: DB_PASS
              value: ${DB_PASSWORD}
          volumeMounts:
            - mountPath: /servico-lanchonete-volume
              name: servico-lanchonete-volume
      volumes:
        - name: servico-lanchonete-volume
          hostPath:
            path: /home/servico-lanchonete-volume
            type: DirectoryOrCreate
  replicas: 2
  selector:
    matchLabels:
      app: servico-lanchonete
